default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: nexoos_development

test:
  <<: *default
  database: nexoos_test

